name: Build and Test on pull request

      
on:
  push:
    branches: ["main","dev","prod-support"]
  pull_request:
    branches: ["main","dev","prod-support"]

env:
  EMAILS: 'sam@semicolon.africa,ladipo@semicolon.africa,t.lemon@semicolon.africa,divinemercy601@gmail.com,qudusa55@gmail.com,o.koleaje@semicolon.africa,ned@semicolon.africa,tade@semicolon.africa,moyinoluwa@semicolon.africa,mariam@semicolon.africa,i.james@semicolon.africa,david@semicolon.africa,abigail@semicolon.africa,precious@semicolon.africa,dapo@semicolon.africa,pauline@semicolon.africa,davidoso@semicolon.africa,henry@semicolon.africa'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --force

      - name: Build
        run: npm run build
        
      - name: Run Unit Tests
        run: npm test -- --ci  

      - name: Set environment variables
        id: vars
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          TAG="commit-${COMMIT_HASH}-timestamp-${TIMESTAMP}"
          echo "TAG=${TAG}" >> $GITHUB_ENV
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

          COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an <%ae>')
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=${COMMIT_AUTHOR}" >> $GITHUB_ENV
          # COMMIT_TITLE=$(git log -1 --pretty=%s)
          # COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          # echo "COMMIT_TITLE=${COMMIT_TITLE}" >> $GITHUB_ENV
          # echo "COMMIT_MESSAGE=${COMMIT_MESSAGE}" >> $GITHUB_ENV


      - name: Debug Environment Variables
        run: |
          echo "TAG=${{ env.TAG }}"
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}"
          echo "COMMIT_TITLE=${{ env.COMMIT_TITLE }}"
          echo "COMMIT_MESSAGE=${{ env.COMMIT_MESSAGE }}"
          echo "COMMIT_AUTHOR=${{ env.COMMIT_AUTHOR }}"
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}"

      - name: Send build success email notification
        if: success()
        env:
          SMTP_SERVER: semicolon.africa
          SMTP_PORT: 465
          SMTP_USERNAME: builds@semicolon.africa
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAILS: ${{ env.EMAILS }}
        run: |
          IFS=',' read -r -a email_array <<< "${EMAILS}"
          for email in "${email_array[@]}"
          do
            echo "From: builds@semicolon.africa" > /tmp/email.txt
            echo "To: $email" >> /tmp/email.txt
            echo "Subject: Build and Deployment Status" >> /tmp/email.txt
            printf "Congratulations, your recent build in Nkwadoma Frontend was successful.\n" >> /tmp/email.txt
            printf "Branch: ${BRANCH_NAME}\n" >> /tmp/email.txt
          
            printf "Author: ${COMMIT_AUTHOR}\n" >> /tmp/email.txt
            printf "\nTAG: ${{ env.TAG }}\n\n" >> /tmp/email.txt
            printf "Regards,\nThe Cloud Team" >> /tmp/email.txt
            curl --verbose --ssl-reqd \
              --url "smtps://${SMTP_SERVER}:${SMTP_PORT}" \
              --mail-from "builds@semicolon.africa" \
              --mail-rcpt "$email" \
              --user "${SMTP_USERNAME}:${SMTP_PASSWORD}" \
              --upload-file /tmp/email.txt
          done

      - name: Send build failure email notification
        if: failure()
        env:
          SMTP_SERVER: semicolon.africa
          SMTP_PORT: 465
          SMTP_USERNAME: builds@semicolon.africa
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAILS: ${{ env.EMAILS }}
        run: |
          IFS=',' read -r -a email_array <<< "${EMAILS}"
          for email in "${email_array[@]}"
          do
            echo "From: builds@semicolon.africa" > /tmp/email.txt
            echo "To: $email" >> /tmp/email.txt
            echo "Subject: Build Failure" >> /tmp/email.txt
            printf "Oooops, Your recent build in Nkwadoma Frontend was unsuccessful, kindly check the new commit and fix.\n\n" >> /tmp/email.txt
            printf "Branch: ${BRANCH_NAME}\n" >> /tmp/email.txt
          
            printf "Author: ${COMMIT_AUTHOR}\n" >> /tmp/email.txt
            printf "\nTAG: ${{ env.TAG }}\n\n" >> /tmp/email.txt
            printf "Regards,\nThe Cloud Team" >> /tmp/email.txt
            curl --verbose --ssl-reqd \
              --url "smtps://${SMTP_SERVER}:${SMTP_PORT}" \
              --mail-from "builds@semicolon.africa" \
              --mail-rcpt "$email" \
              --user "${SMTP_USERNAME}:${SMTP_PASSWORD}" \
              --upload-file /tmp/email.txt
          done
